### ISSUE TITLE
status code 405

### ISSUE THREAD

**Issue by xPx08** [adevjoe/qbittorrent-notify#6]
Tag and notification not working on qbittorrent 4.5.0 on docker (raspberry pi4, bullseye x64).

err, torrents/addTags request fail, status code: 405
![kép_2022-12-05_175258923](https://user-images.githubusercontent.com/110328632/205695328-5f86a9b1-98cb-4664-a025-47311ca19d4b.png)

**Comment by adevjoe** [comment]
seem like addTags api method is wrong on qbittorrent 4.5.0, i'll fix later.

**Comment by adevjoe** [comment]
fix in #7, new image version is `v0.1.3`
